### ISSUE TITLE
bug: categorical data with blank space

### ISSUE THREAD

**Issue by afarnudi** [Penncil/pda#7]
I have a new problem with categorical data when there is blank space in the level names. The error can be regenerated if in the demo/ODACH_CC.R you use:
```R
n_rows <- nrow(odach_cc)
odach_cc$Category <- factor(rep(c("X", "Y Y", "Z"), length.out = n_rows))
```
where I have changed the “Y” factor to “Y Y”. I have many levels with blank spaces in the name.

The error is in the formula construction:
```bash
Error in str2lang(x) : <text>:1:49: unexpected symbol
1: Surv(time, status) ~ X1+GroupB+GroupC+CategoryY Y
```
Where the blank space is messing up the formula!

**Comment by chongliang-luo** [comment]
fixed, please check new demo file
